export const smirnovActions = {
  UPDATE_VALUE: "UPDATE_VALUE",
  SUBMIT_FORM: "SUBMIT_FORM",
  SUCCESS_SMIRNOV: "SUCCESS_SMIRNOV",
  REQUEST_SMIRNOV: "REQUEST_SMIRNOV",
  RESET_SMIRNOV: "RESET_SMIRNOV",
  FAIL_SMIRNOV: "FAIL_SMIRNOV",
  SET_MODAL: "SET_MODAL",

};
