export const frequencyActions = {
    UPDATE_VALUE: "UPDATE_VALUE",
    SUBMIT_FORM: "SUBMIT_FORM",
    SUCCESS_FREQUENCY: "SUCCESS_FREQUENCY",
    REQUEST_FREQUENCY: "REQUEST_FREQUENCY",
    RESET_FREQUENCY: "RESET_FREQUENCY",
    FAIL_FREQUENCY: "FAIL_FREQUENCY",
    SET_MODAL: "SET_MODAL",
  
  };
  