export const generatorActions = {
  UPDATE_VALUE: "UPDATE_VALUE",
  SUBMIT_FORM: "SUBMIT_FORM",
  SUCCESS_GENERATOR: "SUCCESS_GENERATOR",
  REQUEST_GENERATOR: "REQUEST_GENERATOR",
  RESET_GENERATOR: "RESET_GENERATOR",
  FAIL_GENERATOR: "FAIL_GENERATOR",
  SET_DEFAULT_GENERATOR: "SET_DEFAULT_GENERATOR",
  SAVE_PSEUDO_NUMBERS: "SAVE_PSEUDO_NUMBERS"
};
